from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import RedirectResponse

from ..database import get_db
from ..models import AppSettings

router = APIRouter(prefix="/api/settings", tags=["settings"])

_SENSITIVE = {"openai_api_key", "youtube_client_secret", "youtube_refresh_token"}
_MASK = "••••••••"

# In-memory storage for OAuth PKCE state (since it's a single-tenant local app)
_OAUTH_STATE = {}


@router.get("")
async def get_settings() -> dict:
    db = get_db()
    doc = (await db.app_settings.find_one({"_id": "main"})) or {}
    doc.pop("_id", None)
    for k in _SENSITIVE:
        if doc.get(k):
            doc[k] = _MASK
    return doc


@router.put("")
async def save_settings(body: AppSettings) -> dict:
    db = get_db()
    data = body.model_dump(exclude_none=True)

    # Preserve existing values when frontend sends back masked placeholder
    existing = (await db.app_settings.find_one({"_id": "main"})) or {}
    for k in _SENSITIVE:
        if data.get(k) == _MASK:
            if existing.get(k):
                data[k] = existing[k]
            else:
                data.pop(k, None)

    await db.app_settings.replace_one(
        {"_id": "main"},
        {"_id": "main", **data},
        upsert=True,
    )
    return {"status": "saved"}


@router.post("/test-youtube")
async def test_youtube() -> dict:
    from ..pipeline.uploader import test_credentials

    db = get_db()
    cfg = (await db.app_settings.find_one({"_id": "main"})) or {}

    client_id = cfg.get("youtube_client_id")
    client_secret = cfg.get("youtube_client_secret")
    refresh_token = cfg.get("youtube_refresh_token")

    if not all([client_id, client_secret, refresh_token]):
        return {"ok": False, "error": "Credenciais não configuradas"}

    ok = test_credentials(client_id, client_secret, refresh_token)
    return {"ok": ok, "error": None if ok else "Credenciais inválidas"}


@router.get("/youtube/auth")
async def youtube_auth(request: Request):
    """Generates the Google OAuth2 consent screen URL."""
    try:
        from google_auth_oauthlib.flow import Flow
    except ImportError:
        raise HTTPException(500, "google-auth-oauthlib not installed")

    db = get_db()
    cfg = (await db.app_settings.find_one({"_id": "main"})) or {}

    client_id = cfg.get("youtube_client_id")
    client_secret = cfg.get("youtube_client_secret")

    if not client_id or not client_secret:
        raise HTTPException(400, "Client ID e Client Secret não configurados")

    base_url = str(request.base_url).rstrip("/")
    redirect_uri = f"{base_url}/api/settings/youtube/callback"

    client_config = {
        "installed": {
            "client_id": client_id,
            "client_secret": client_secret,
            "redirect_uris": [redirect_uri],
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
        }
    }

    flow = Flow.from_client_config(
        client_config,
        scopes=["https://www.googleapis.com/auth/youtube.upload"],
        redirect_uri=redirect_uri,
    )

    auth_url, state = flow.authorization_url(
        access_type="offline",
        prompt="consent",
        include_granted_scopes="true",
    )

    # Save the PKCE verifier generated by the flow (required for Desktop clients)
    _OAUTH_STATE["code_verifier"] = getattr(flow, "code_verifier", None)

    return RedirectResponse(auth_url)


@router.get("/youtube/callback")
async def youtube_callback(request: Request, code: str):
    """Exchanges the authorization code for a refresh token."""
    try:
        from google_auth_oauthlib.flow import Flow
    except ImportError:
        raise HTTPException(500, "google-auth-oauthlib not installed")

    db = get_db()
    cfg = (await db.app_settings.find_one({"_id": "main"})) or {}

    client_id = cfg.get("youtube_client_id")
    client_secret = cfg.get("youtube_client_secret")

    if not client_id or not client_secret:
        raise HTTPException(400, "Client ID e Client Secret não configurados")

    base_url = str(request.base_url).rstrip("/")
    redirect_uri = f"{base_url}/api/settings/youtube/callback"

    client_config = {
        "installed": {
            "client_id": client_id,
            "client_secret": client_secret,
            "redirect_uris": [redirect_uri],
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
        }
    }

    flow = Flow.from_client_config(
        client_config,
        scopes=["https://www.googleapis.com/auth/youtube.upload"],
        redirect_uri=redirect_uri,
    )

    # Restore the PKCE verifier from the auth step
    verifier = _OAUTH_STATE.get("code_verifier")
    if verifier:
        flow.code_verifier = verifier

    try:
        flow.fetch_token(code=code)
        creds = flow.credentials

        # Save refresh token to db
        await db.app_settings.update_one(
            {"_id": "main"},
            {"$set": {"youtube_refresh_token": creds.refresh_token}},
            upsert=True
        )

        return RedirectResponse("/settings?youtube_auth=success")
    except Exception as e:
        return RedirectResponse(f"/settings?youtube_auth=error&msg={str(e)}")
